name: padavanonly_sync

on:
  push:
    paths:
      - '.github/workflows/padavanonly_sync.yml'
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  job_Sync:
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
    runs-on: ubuntu-latest

    name: Clone and push openwrt-24.10 branch
    steps:
    - name: Set git identity and timezone
      run: |
        git config --global user.email "zhiern@users.noreply.github.com"
        git config --global user.name "actions-user"
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: Clone upstream with full history
      run: |
        git clone --branch openwrt-24.10-6.6 https://github.com/padavanonly/immortalwrt-mt798x-24.10.git upstream
        cd upstream

    - name: Push to KejiZero Git Server
      env:
        ACCESS_TOKEN: ${{ secrets.TOKEN_zhiern }}
      run: |
        cd upstream
        git remote add openwrt-24.10 https://zhao:zj3753813@git.kejizero.online/zhao/immortalwrt-mt798x-24.10.git
        git push openwrt-24.10 openwrt-24.10:refs/heads/openwrt-24.10

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
